apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubpf-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: githubpf
  template:
    metadata:
      labels:
        app: githubpf
    spec:
      containers:
        - name: githubpf
          image: yash5090/githubpf:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
